CRM/CRM/urls.py
from os import stat
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignUpView
from django.contrib.auth.views import (
    LoginView,
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView 

)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name = "landing_page"),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name = "login"),   
    path('logout/', LogoutView.as_view(), name = "logout"),
    path('signup/',SignUpView.as_view(), name = "signup"),
    path('password-reset/',PasswordResetView.as_view(), name ="password-reset"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name ="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name = "password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name ="password_reset_complete"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

CRM/agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView,AgentDeleteView

app_name = "agents"



urlpatterns = [
    path('', AgentListView.as_view(), name = "agent-list"),
    path('create/',AgentCreateView.as_view(), name = 'agent-create'),
    path('<int:pk>/',AgentDetailView.as_view(), name = "agent-details" ),
    path('<int:pk>/update',AgentUpdateView.as_view(), name = "agent-update" ),
    path('<int:pk>/delete',AgentDeleteView.as_view(), name = "agent-delete" ),
]

CRM/leads/urls.py
from leads.models import Lead
from django.urls import path
from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AgentUpdateView,CategoryListView,CategoryDetailView,CategoryUpdateView

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name = 'lead-list'),
    path('<int:pk>/',LeadDetailView.as_view(),name = 'lead-detail'),
    path('create/',LeadCreateView.as_view(), name = 'lead-create'),
    path('<int:pk>/update/',LeadUpdateView.as_view(), name = 'lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name = 'lead-delete'),
    path('<int:pk>/agent-update/',AgentUpdateView.as_view(), name = "agent-update"),
    path('categories/', CategoryListView.as_view(), name ="categories"),
    path('<int:pk>/categories_details/',CategoryDetailView.as_view(), name= "category-detail"),
    path('<int:pk>/category_update/',CategoryUpdateView.as_view(), name = "category-update"),
]

CRM/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang = "eng">
    <head>
        <meta charset="UTF-8">
        <meta name = "viewport" content="width = device-width, initial-scale = 1.0">
        <title>CRM application</title>
        <link href = "{% static 'css/style.css' %}"/>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body>
    <div class = "max-w-6xl mx-auto">
    {% include 'navbar.html' %}
     {% block content %}
     {% endblock content %}
    </div>
    </body>
</html>

CRM/templates/landing.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
  
    <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900 mx-auto">CRM made with Django 
        <br class="hidden lg:inline-block">
      </h1>
      <p class="mb-8 leading-relaxed mx-auto">This application helps to manage leads and clients
      </p>
      <button class = "w-1/4 bg-blue-500 text-white hover:bg-blue-600 px-3 py-2 rounded-md mx-auto" type="submit"><a href = "{% url 'login' %}">Login to start</a></button>
    </div>
  </div>
</section>
{% endblock %}

CRM/templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-pink-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">DJ CRM</span>
    </a>
    {% if not request.user.is_authenticated %}
    <a href = "{% url 'signup' %}" class = "inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">SignUp Here</a>
    
    {% else %}
    <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
    {% if request.user.is_organizer %}
     <a  href = "{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
    {% endif %}
        <a  href = "{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
    </nav>
    {% endif %}
    {% if request.user.is_authenticated %}
     Logged in as {{request.user.username}}
    <a href = "{% url 'logout' %}" class="ml-2 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">LogOut
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
    <a href = "{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">LogIn
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>