CRM/CRM/urls.py
from os import stat
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignUpView
from django.contrib.auth.views import (
    LoginView,
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView 

)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name = "landing_page"),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name = "login"),   
    path('logout/', LogoutView.as_view(), name = "logout"),
    path('signup/',SignUpView.as_view(), name = "signup"),
    path('password-reset/',PasswordResetView.as_view(), name ="password-reset"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name ="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name = "password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name ="password_reset_complete"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

CRM/leads/urls.py
from leads.models import Lead
from django.urls import path
from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AgentUpdateView,CategoryListView,CategoryDetailView,CategoryUpdateView

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name = 'lead-list'),
    path('<int:pk>/',LeadDetailView.as_view(),name = 'lead-detail'),
    path('create/',LeadCreateView.as_view(), name = 'lead-create'),
    path('<int:pk>/update/',LeadUpdateView.as_view(), name = 'lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name = 'lead-delete'),
    path('<int:pk>/agent-update/',AgentUpdateView.as_view(), name = "agent-update"),
    path('categories/', CategoryListView.as_view(), name ="categories"),
    path('<int:pk>/categories_details/',CategoryDetailView.as_view(), name= "category-detail"),
    path('<int:pk>/category_update/',CategoryUpdateView.as_view(), name = "category-update"),
]

CRM/leads/models.py
from django.db import models
from django.db.models.fields import CharField
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
# Create your models here.
 
class User(AbstractUser):
    is_organizer = models.BooleanField(default = True)
    is_agent = models.BooleanField(default = False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default= 0)
    organization = models.ForeignKey(UserProfile, null = True, on_delete = models.CASCADE)
    agent = models.ForeignKey("Agent", blank = True, null= True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name = "leads", blank = True, null= True,on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Category(models.Model):  #new, contacted, converted, unconverted(types of category)
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete = models.CASCADE)

    def __str__(self):
        return self.user.email

def create_userprofile(sender,instance,created, **kwargs):
    if created:
        UserProfile.objects.create(user = instance)

    
post_save.connect(create_userprofile, sender = User)

CRM/leads/forms.py
from django import forms
from .models import Lead, User, Agent
from django.contrib.auth.forms import UserCreationForm, UsernameField

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("first_name", "last_name", "age", "agent")


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}



class AgentUpdateForm(forms.Form):
    agent = forms.ModelChoiceField(queryset = Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organization = request.user.userprofile)
        super(AgentUpdateForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class CategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)

CRM/leads/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, request
from .models import Lead, Agent, User,Category
from .forms import LeadForm, LeadModelForm,CustomUserCreationForm, AgentUpdateForm,CategoryUpdateForm
from django.views import generic
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganizerorLoginRequiredMixin

#Create Read Update Delete + Listview

#view for signup
class SignUpView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

# Create your views here.
class LandingPageView(generic.TemplateView):
    template_name = "landing.html"



# def landing_page(request):
#     return render(request, "landing.html")


class LeadListView(LoginRequiredMixin,generic.ListView):
    template_name = "leads/lead-list.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization = user.userprofile, agent__isnull = False)
        else:
            queryset = Lead.objects.filter(organization =user.agent.organization, agent__isnull = False)
            queryset = queryset.filter(agent__user = user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization = user.userprofile, agent__isnull = True)
            context.update({
                'unassigned_leads': queryset
            })
        return context
# def lead_list(request):
#     leads = Lead.objects.all()
#     context ={
#         "leads": leads
#     }
#     return render(request, "leads/lead_list.html", context)

class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_details.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization = user.userprofile)
        else:
            queryset = Lead.objects.filter(organization =user.agent.organization)
            queryset = queryset.filter(agent__user = user)
        return queryset


# def lead_detail(request, pk):
#     lead = Lead.objects.get(id = pk)
#     context = {
#         "lead":lead
#     }
#     return render(request, "leads/lead_details.html", context)



class LeadCreateView(OrganizerorLoginRequiredMixin,generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm
    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit = False)
        lead.organization = self.request.user.userprofile
        lead.save()
        
        subject = "A new lead has been created"
        message = "Go to the crm site to view the new lead details"
        from_email = "test@test.com"
        recipient_list = ["test2@test.com"]
        send_mail(subject, message, from_email, recipient_list)
        # we want to send email whenever a lead is created 

        return super(LeadCreateView, self).form_valid(form)


def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        print("Receiving a post request")
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)


class LeadUpdateView(OrganizerorLoginRequiredMixin,generic.UpdateView):
    template_name = "leads/lead_update.html"
    queryset = Lead.objects.all()
    form_class = LeadModelForm
    context_object_name = "lead"

    def get_success_url(self):
        return reverse("leads:lead-list")
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization = user.userprofile)



def lead_update(request, pk):
    lead = Lead.objects.get(id = pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance= lead)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context = {
        'form':form,
        'lead':lead
    }
    return render(request, "leads/lead_update.html", context)


class LeadDeleteView(OrganizerorLoginRequiredMixin,generic.DeleteView):
    template_name = "leads/lead_delete.html"
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization = user.userprofile)

    def get_success_url(self):
        return reverse('leads:lead-list')

def lead_delete(request, pk):
    lead = Lead.objects.get(id = pk)
    lead.delete()
    return redirect('/leads')

# lead = Lead.objects.get(id = pk)
#     form = LeadForm()
#     if request.method == 'POST':
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             lead.first_name = first_name
#             lead.last_name = last_name
#             lead.age = age
#             lead.save()
#             return redirect('/leads')
#     context = {
#         "lead": lead,
#         "form":form
#     }
#     return render(request, "leads/lead_update.html", context)


class AgentUpdateView(OrganizerorLoginRequiredMixin, generic.FormView):
    template_name = "leads/agent_update.html"
    form_class = AgentUpdateForm

    def get_form_kwargs(self,**kwargs):
        kwargs = super(AgentUpdateView,self).get_form_kwargs(**kwargs)
        kwargs.update(
            {
                "request":self.request
            }
        )
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id = self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AgentUpdateView, self).form_valid(form)



class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/category_lists.html'
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):

        context = super(CategoryListView, self).get_context_data(**kwargs)

        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(organization = user.userprofile)
        else:
            queryset = Lead.objects.filter(organization =user.agent.organization)

        context.update(
            {
                'unassigned_lead_count':queryset.filter(category__isnull = True).count()
            }
        )
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Category.objects.filter(organization = user.userprofile)
        else:
            queryset = Category.objects.filter(organization =user.agent.organization)
        return queryset

class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_details.html"
    context_object_name = "category"

    #This get_context_data can be simply overriden using category.leads.all in the templates
    # def get_context_data(self, **kwargs):
    #     context = super(CategoryDetailView, self).get_context_data(**kwargs)
    #     leads = self.get_object().leads.all()
    #     context.update({
    #         "leads": leads
    #     })
    #     return context


    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Category.objects.filter(organization = user.userprofile)
        else:
            queryset = Category.objects.filter(organization =user.agent.organization)
        
        return queryset

class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/category_update.html"
    form_class = CategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization = user.userprofile)
        else:
            queryset = Lead.objects.filter(organization = user.agent.userprofile)
            queryset = queryset.filter(agent__user = user)
        return queryset

    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs = { "pk" :self.get_object().id})

CRM/leads/templates/leads/agent_update.html
{% extends 'base.html' %}
 {% block content %} 

 {% load tailwind_filters %}

<div class="max-w-lg mx-auto">
    <div class="mt-3 mb-2">
  <a class = "text-black-600 underline hover:text-red-600" href="{%url 'leads:lead-list' %}"> Go back to the leads</a>
   </div>
<div class="flex justify-center mt-2 mb-3">
    <h1 class ="text-black-600" >Assign an agent to this lead</h1>
</div>
  <form method="POST">
    {% csrf_token %} 

    {{ form|crispy }}

    <button type="submit">Update</button>
  </form>
</div>

{% endblock %}

CRM/leads/templates/leads/category_details.html
{% extends 'base.html' %}

{% block content %}
<br />
<div class="container flex justify-center mx-auto">
    <h1>{{category.name}}</h1>
</div>
<br />
<div class="container flex justify-center mx-auto">
    <h2>The leads under this category are:  </h2>
</div>
<br />
<div class="container flex justify-center mx-auto">
    <div class="flex flex-col">
        <div class="w-full">
            <div class="border-b border-gray-200 shadow">
                <table>
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="px-6 py-2 text-xs text-gray-500">
                                First name
                            </th>
                            <th class="px-6 py-2 text-xs text-gray-500">
                                Last Name
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white">

                        {% for lead in  category.leads.all %}
                        
                        <tr class="whitespace-nowrap">
                            <td class="px-6 py-4 text-sm text-gray-500">
                                <a class ="hover:text-red-700" href = {% url 'leads:lead-detail' lead.pk %}>
                                {{lead.first_name}}
                            </a></td> 
                            <td class="px-6 py-4">
                                <div class="text-sm text-gray-900">
                                {{lead.last_name}}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

CRM/leads/templates/leads/category_list.html
{% extends 'base.html' %}

{% block content %}
<br />
<div class="container flex justify-center mx-auto">
    <h1>Categories</h1>
</div>
<br />
<div class="container flex justify-center mx-auto">
    <h2>The categories of leads are listed below: </h2>
</div>
<br />
<div class="container flex justify-center mx-auto">
    <div class="flex flex-col">
        <div class="w-full">
            <div class="border-b border-gray-200 shadow">
                <table>
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="px-6 py-2 text-xs text-gray-500">
                                Name
                            </th>
                            <th class="px-6 py-2 text-xs text-gray-500">
                                Lead Count
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white">
                        <tr>
                            <td class = "px-6 py-4 text-sm text-gray-500">Uncategorized leads</td>
                            <td class="px-6 py-4 text-sm text-gray-500">{{unassigned_lead_count}}</td>
                        <tr>
                        {% for category in category_list %}
                        <tr class="whitespace-nowrap">
                           <td> <a class="px-6 py-4 text-sm text-gray-500" href = {% url 'leads:category-detail' category.pk %}> {{category.name}} </a></td>
                            <td class="px-6 py-4">
                                <div class="text-sm text-gray-900">TODO count</div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

CRM/leads/templates/leads/category_update.html
{% extends 'base.html' %} {% block content %}
{% load tailwind_filters %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{lead.first_name}} {{lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a href ={% url 'leads:lead-detail' lead.pk %} class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Lead Details</a
          >
          <a  href ={% url 'leads:category-update' lead.pk %} class="
          flex-grow
          text-indigo-500
          border-b-2 border-indigo-500
          py-2
          text-lg
          px-1
        "
            >Category</a
          >
          <a href = {% url 'leads:lead-update' lead.pk %} class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Update</a
          >
        </div>
        <form method="POST" action=".">
            {% csrf_token %}
             {{ form|crispy }}
            <div class = "flex justify-between">
           <button class = "ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"type = "submit">Update</button>
            </div>
            </form>
            <div class = "flex justify-between">
            <a href="{% url 'leads:lead-list' %}" class = " ml-auto mt-5 text-white bg-yellow-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit">Go back to leads</a>
        </div>
  </div>
</section>
{% endblock %}

CRM/leads/templates/leads/lead_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class = "max-w-lg mx-auto">
    <div class = "mt-3">
    <a class ="text-blue-500 hover:text-red-500 underline" href= "{%url 'leads:lead-list' %}"> Go back to the leads</a>
    </div>
    <div class = "mb-4 mt-3 flex justify-center" >
<h1 class = "text-black-600" >Create a new lead here </h1>
    </div>
<form method = "POST" action = ".">
    {% csrf_token %} 
    {{ form|crispy }}

    <button class = "w-full bg-green-500 hover:bg-yellow-500 text-white px-3 py-2 rounded-md" type="submit">Submit</button>
</form>
</div>
{% endblock %}

CRM/leads/templates/leads/lead_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<div class = "max-w-lg mx-auto">
   <div class = "mt-3">
    <a class ="text-blue-500" href= "{%url 'leads:lead-list' %}"> Go back to the leads</a>
    <div>
    <h1 class = "text-black-500">Are you sure you want to delete this lead? </h1>
    <form method = "POST">
        {% csrf_token %} 
        {{ form|crispy }}
        <div class = "mx-5">
        <button class ="bg-red-500 text-white px-3 rounded-md" type="submit">Yes</button>
        <button class ="bg-green-500 text-white px-3 rounded-md"><a href = "{%url 'leads:lead-detail' lead.pk %}">No</a></button>
        </div>
    </form>
        </div>

</div>



{% endblock %}

CRM/leads/templates/leads/lead_details.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Lead Details</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" href = "{% url 'leads:category-update' lead.pk %}">Category</a>
            <a href = " {% url 'leads:lead-update' lead.pk %} "class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Color</span>
            <span class="ml-auto text-gray-900">Blue</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{lead.age}}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">dummy_location</span>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>









    <a href= "{% url 'leads:lead-list' %}"> Go back to the leads</a>
    <br />
<h1>This is the details of {{lead.first_name}} </h1>
<h3>The age of this person is {{lead.age}}</h3>
<h3>The agent responsible for this lead is {{lead.agent}}</h3>
<hr />
<a href = "{% url 'leads:lead-update' lead.pk %}">Update Leads</a>
<a href = "{% url 'leads:lead-delete' lead.pk %}">Delete Leads</a>

{% endblock %}

CRM/leads/templates/leads/lead_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class = "w-full mb-1 py-6 flex justify-between items-center border-b border-blue-200">
            <div>
            <h1 class = "text-4xl text-pink-700"> Leads </h1>
            <h3 class = "text-black-300 underline"><a href = {% url 'leads:categories' %}>View Category</a></h3>
            </div>
              
            {% if request.user.is_organizer %}
            <div>
            <a class = "text-gray-600 hover:text-pink-500" href = "{% url 'leads:lead-create' %}"> Create a new lead </a>
            </div>
            {% endif %}
        </div>
    <div class="flex flex-wrap -m-4">
        {% for lead in leads %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}}  {{lead.lastname}} {{lead.age}}</h2>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href = "{% url 'leads:lead-detail' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">View this lead
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
        {% if unassigned_leads.exists %}

        <div class="flex flex-wrap -m-4">
        <div class = "p-4 w-full">
        <h1 class = "text-4xl text-pink-700"> Unassigned Leads</h1>
        </div>
        {% for lead in unassigned_leads %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}}  {{lead.lastname}} {{lead.age}}</h2>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href = "{% url 'leads:agent-update' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">update the agent
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
</div>
  </section>

{% endblock content %}

CRM/leads/templates/leads/lead_update.html
{% extends 'base.html' %} {% block content %}

{% load tailwind_filters %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{lead.first_name}} {{lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a href ={% url 'leads:lead-detail' lead.pk %} class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Lead Details</a
          >
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"  href ={% url 'leads:category-update' lead.pk %} 
            >Category</a
          >
          <a href = {% url 'leads:lead-update' lead.pk %}
          class="
          flex-grow
          text-indigo-500
          border-b-2 border-indigo-500
          py-2
          text-lg
          px-1
        "
            >Update</a
          >
        </div>
        <form method="POST" action=".">

            {% csrf_token %}
            
            {{ form|crispy }}

            <div class = "flex justify-between">
           <button class = "ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"type = "submit">Update</button>
            </div>
            </form>
            <div class = "flex justify-between">
            <a href="{% url 'leads:lead-list' %}" class = " ml-auto mt-5 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit">Go back to leads</a>
        </div>
  </div>
</section>
{% endblock %}