CRM/CRM/urls.py
from os import stat
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignUpView
from django.contrib.auth.views import (
    LoginView,
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView 

)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name = "landing_page"),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name = "login"),   
    path('logout/', LogoutView.as_view(), name = "logout"),
    path('signup/',SignUpView.as_view(), name = "signup"),
    path('password-reset/',PasswordResetView.as_view(), name ="password-reset"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name ="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name = "password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name ="password_reset_complete"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

CRM/agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView,AgentDeleteView

app_name = "agents"



urlpatterns = [
    path('', AgentListView.as_view(), name = "agent-list"),
    path('create/',AgentCreateView.as_view(), name = 'agent-create'),
    path('<int:pk>/',AgentDetailView.as_view(), name = "agent-details" ),
    path('<int:pk>/update',AgentUpdateView.as_view(), name = "agent-update" ),
    path('<int:pk>/delete',AgentDeleteView.as_view(), name = "agent-delete" ),
]

CRM/agents/models.py
from django.db import models

# Create your models here.

CRM/agents/forms.py
from django import forms

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )

CRM/agents/views.py
from django.shortcuts import render,reverse
from leads.models import Agent
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AgentModelForm
from .mixins import OrganizerorLoginRequiredMixin
from  django.core.mail import send_mail
import random
# Create your views here.

class AgentListView(OrganizerorLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        orgs = self.request.user.userprofile
        return Agent.objects.filter(organization = orgs)


class AgentCreateView(OrganizerorLoginRequiredMixin, generic.CreateView):
    template_name  ='agents/agent_create.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agent-list')

    def form_valid(self, form):
        user = form.save(commit = False)
        user.is_agent = True
        user.is_organizer = False
        user.save()
        user.set_password(f"{random.randint(0,100000)}")
        Agent.objects.create(user = user, organization = self.request.user.userprofile)

        send_mail(
            subject= "Invited as an agent",
            message = "You are invited as an agent. Please login to start working as an agent", 
            from_email="master@mail.com",
            recipient_list=[user.email]       
        )
        # agent.organization = self.request.user.userprofile
        # agent.save()
        return super(AgentCreateView, self).form_valid(form)

class AgentDetailView(OrganizerorLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/agent_details.html'
    context_object_name = "agent"

    def get_queryset(self):
        return Agent.objects.all()


class AgentUpdateView(OrganizerorLoginRequiredMixin, generic.UpdateView):
    template_name  ='agents/agent_update.html'
    context_object_name = "agent"
    form_class = AgentModelForm

    def get_queryset(self):
        return Agent.objects.all()

    def get_success_url(self):
        return reverse('agents:agent-list')

class AgentDeleteView(OrganizerorLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_success_url(self):
        return reverse('agents:agent-list')
        
    def get_queryset(self):
        return Agent.objects.all()

CRM/agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class = "max-w-lg mx-auto">
    <div class = "mx-auto mb-3">
    <a class ="text-black-600 hover:text-blue-600 underline" href= "{%url 'agents:agent-list' %}"> Go back to the agents</a>
    </div>
    <div class = "grid place-items-center mb-4 mt-2">
<h1 class ="text-black-800">Create a new agent here </h1>
    </div>
<form method = "POST">
    {% csrf_token %} 
    {{ form|crispy }}
    <button class = "w-full bg-yellow-500 text-white hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">Submit</button>
</form>
</div>
{% endblock %}

CRM/agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class = "max-w-lg mx-auto">
    <div class = "mx-auto mb-3">
    <a class ="text-black-600 hover:text-blue-600 underline" href= "{%url 'agents:agent-list' %}"> Go back to the leads</a>
    </div>
    <div class = "flex mt -5">
    <h1 class ="text-black-800">Are you sure you want to delete this lead? </h1>
<form method = "POST">
    {% csrf_token %} 
    {{ form|crispy }}
    
    <div class = "mx-5">
        <button class ="bg-red-500 text-white px-3 rounded-md" type="submit">Delete</button>
        <button class ="bg-green-500 text-white px-3 rounded-md"><a href = "{%url 'agents:agent-details' agent.pk %}">No</a></button>
    </div>
</div>
</form>
</div>
{% endblock %}

CRM/agents/templates/agents/agent_details.html
{% extends 'base.html' %}

{% block content %}

{% load tailwind_filters %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Agent Details</a>
            <a href = "{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Color</span>
            <span class="ml-auto text-gray-900">Blue</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{lead.age}}</span>
          </div>
        </div>
      </div>
    </div>
  </section>

 <a href= "{% url 'agents:agent-list' %}"> Go back to the leads</a>
<br />
<h1>This is the details of {{agent.user.username}} </h1>
<hr />
<a href = "{%url 'agents:agent-update' agent.pk%}">Update Agent</a>
<a href = "{%url 'agents:agent-delete' agent.pk%}">Delete Agent</a>

{% endblock %}

CRM/agents/templates/agents/agent_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class = "w-full mb-1 py-6 flex justify-between items-center border-b border-blue-200">
            <div>
            <h1 class = "text-4xl text-pink-700"> Agents </h1>
            </div>
            <div>
            <a class = "text-gray-600 hover:text-pink-500" href = "{% url 'agents:agent-create' %}"> Create a new agent</a>
            </div>
        </div>
    </div>
    <div class="flex flex-wrap -m-4">
        {% for agent in object_list %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}</h2>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href = "{%url 'agents:agent-details' agent.pk%}" class="mt-3 text-indigo-500 inline-flex items-center">View this agent
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

{% endblock content %}

CRM/agents/templates/agents/agent_update.html
{% extends 'base.html' %}
{% block content %}
{% load tailwind_filters %}
<div class="max-w-lg mx-auto">

<section class="text-gray-600 body-font">
  <div class="">
    <div class="">
      <div class="">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{agent.user.username}}
        </h1>
        <div class="flex mb-4">
          <a href ={% url 'agents:agent-details' agent.pk %} class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Agent Details</a>
          <a class=
          "
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            "
            >Update</a
          >
        </div>
        <form method="POST">
            {% csrf_token %}

             {{ form|crispy }}

            <div class = "flex justify-between">
           <button class = "w-full ml-auto text-white bg-yellow-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type = "submit">Update</button>
            </div>
            
            <div class = "mt-4 flex justify-between">
            <a href="{% url 'agents:agent-list' %}" class = "w-full text-center ml-auto text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit">Go back to agents</a>
        </div>
      </form>
  </div>
</section>

</div>
{% endblock %}